### PR TITLE
Next.js rewrite

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Can't assign @akisblack so I'll just ping him

**Comment by Midou36O** [comment]
For archival reasons move the golang version of it to a separate branch before merging it to main alright?

**Comment by ghost** [comment]
do whatever you think is best

**Comment by ghost** [comment]
although, commit history exists so i dont see the purpose of doing that

**Comment by ghost** [comment]
also it's Go not golang

**Comment by Midou36O** [comment]
> although, commit history exists so i dont see the purpose of doing that

tagging would better then

**Comment by ghost** [comment]
Forgot to say. Yep, this is kind of a joke PR, there is no way we will use Next.js for Segfautils because the Docker image will be too massive and it's just not necessary. What we will do is make a rewrite in Fiber, however I'm not exactly motivated to work on this project unless akis really pushes me to. Sorry for wasting your time, if I did

**Pull request closed without merging**
